name: bld
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - numpy
  - pip
  - pip:
      - einops==0.8.0
      - diffusers==0.19.3
      - transformers==4.29.2
      - huggingface_hub==0.15.1
      - omegaconf==2.3.0
      - opencv-python