name: diffinpainting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - diffusers==0.19.3
      - transformers==4.29.2
      - einops==0.3.0
      - huggingface-hub==0.23.4
      - omegaconf==2.3.0
      - opencv-python