name: gligen
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - diffusers==0.24.0
      - transformers==4.27.1
      - einops==0.3.0
      - huggingface-hub==0.24.5
      - opencv-python==4.10.0.84
      - omegaconf==2.1.1
      - opencv-python
      - clip
      - kornia
